import api from './index.js'

export const getKafkaClusters = (params) => api.get('/kafka/clusters', { params })
export const getKafkaCluster = (id) => api.get(`/kafka/clusters/${id}`)
export const createKafkaCluster = (data) => api.post('/kafka/clusters', data)
export const updateKafkaCluster = (id, data) => api.put(`/kafka/clusters/${id}`, data)
export const deleteKafkaCluster = (id) => api.delete(`/kafka/clusters/${id}`)
export const testKafkaCluster = (id) => api.post(`/kafka/clusters/${id}/test`)
export const getKafkaClusterOptions = () => api.get('/kafka/clusters/options')
export const getKafkaDashboard = (clusterId) => api.get('/kafka/dashboard', { params: { clusterId } })
export const getKafkaHealthOverview = (clusterId) => api.get('/kafka/health', { params: { clusterId } })
export const getKafkaTrendSeries = (params) => api.get('/kafka/trends', { params })
export const scanKafkaNetwork = (data) => api.post('/kafka/discovery/scan', data)
export const importKafkaDiscoveryResult = (data) => api.post('/kafka/discovery/import', data)
export const createKafkaTopic = (data) => api.post('/kafka/topics', data)
export const getKafkaTopics = (params) => api.get('/kafka/topics', { params })
export const deleteKafkaTopic = (clusterId, topic) => api.delete(`/kafka/topics/${encodeURIComponent(topic)}`, { params: { clusterId } })
export const updateKafkaTopicConfig = (topic, data) => api.put(`/kafka/topics/${encodeURIComponent(topic)}/config`, data)
export const getKafkaTopicPartitions = (clusterId, topic) => api.get(`/kafka/topics/${encodeURIComponent(topic)}/partitions`, { params: { clusterId } })
export const increaseKafkaTopicPartitions = (topic, data) => api.post(`/kafka/topics/${encodeURIComponent(topic)}/partitions`, data)
export const getKafkaBrokers = (clusterId) => api.get('/kafka/brokers', { params: { clusterId } })
export const getKafkaConsumerGroups = (params) => api.get('/kafka/consumer-groups', { params })
export const getKafkaConsumerGroupDetail = (groupId, params) => api.get(`/kafka/consumer-groups/${encodeURIComponent(groupId)}`, { params })
export const resetKafkaGroupOffset = (groupId, data) => api.post(`/kafka/consumer-groups/${encodeURIComponent(groupId)}/reset-offset`, data)
export const getKafkaMessages = (params) => api.get('/kafka/messages', { params })
export const produceKafkaMessage = (data) => api.post('/kafka/messages/produce', data)
export const getKafkaAuditLogs = (params) => api.get('/kafka/audit-logs', { params })
export const getKafkaAlertRules = (params) => api.get('/kafka/alert-rules', { params })
export const createKafkaAlertRule = (data) => api.post('/kafka/alert-rules', data)
export const updateKafkaAlertRule = (id, data) => api.put(`/kafka/alert-rules/${id}`, data)
export const deleteKafkaAlertRule = (id) => api.delete(`/kafka/alert-rules/${id}`)
export const evaluateKafkaAlertRules = (data) => api.post('/kafka/alert-rules/evaluate', data)
export const getKafkaAlertSilences = (params) => api.get('/kafka/alert-silences', { params })
export const createKafkaAlertSilence = (data) => api.post('/kafka/alert-silences', data)
export const updateKafkaAlertSilence = (id, data) => api.put(`/kafka/alert-silences/${id}`, data)
export const deleteKafkaAlertSilence = (id) => api.delete(`/kafka/alert-silences/${id}`)
export const getKafkaAlertEvents = (params) => api.get('/kafka/alert-events', { params })
export const updateKafkaAlertEventStatus = (id, data) => api.put(`/kafka/alert-events/${id}/status`, data)
export const getKafkaTraceLinks = (params) => api.get('/kafka/traces', { params })
export const createKafkaTraceLink = (data) => api.post('/kafka/traces', data)
export const deleteKafkaTraceLink = (id) => api.delete(`/kafka/traces/${id}`)
export const getKafkaScalingRecommendations = (params) => api.get('/kafka/scaling-recommendations', { params })
export const runKafkaInspection = (data) => api.post('/kafka/inspections/run', data)
export const getKafkaInspectionReports = (params) => api.get('/kafka/inspections', { params })
export const getKafkaInspectionReport = (id) => api.get(`/kafka/inspections/${id}`)
export const getKafkaSelfHealingPolicies = (params) => api.get('/kafka/self-healing-policies', { params })
export const createKafkaSelfHealingPolicy = (data) => api.post('/kafka/self-healing-policies', data)
export const updateKafkaSelfHealingPolicy = (id, data) => api.put(`/kafka/self-healing-policies/${id}`, data)
export const deleteKafkaSelfHealingPolicy = (id) => api.delete(`/kafka/self-healing-policies/${id}`)
export const executeKafkaSelfHealingPolicy = (id) => api.post(`/kafka/self-healing-policies/${id}/execute`)
export const getKafkaSelfHealingExecutions = (params) => api.get('/kafka/self-healing-executions', { params })
export const getKafkaTasks = (params) => api.get('/kafka/tasks', { params })
export const createKafkaTask = (data) => api.post('/kafka/tasks', data)
export const updateKafkaTask = (id, data) => api.put(`/kafka/tasks/${id}`, data)
export const deleteKafkaTask = (id) => api.delete(`/kafka/tasks/${id}`)
export const runKafkaTask = (id, data = {}) => api.post(`/kafka/tasks/${id}/run`, data)
export const getKafkaTaskRuns = (params) => api.get('/kafka/task-runs', { params })
export const getKafkaChangeRequests = (params) => api.get('/kafka/change-requests', { params })
export const createKafkaChangeRequest = (data) => api.post('/kafka/change-requests', data)
export const reviewKafkaChangeRequest = (id, data) => api.put(`/kafka/change-requests/${id}/review`, data)
export const executeKafkaChangeRequest = (id) => api.post(`/kafka/change-requests/${id}/execute`)
export const getKafkaTopicMetadata = (params) => api.get('/kafka/topic-metadata', { params })
export const createKafkaTopicMetadata = (data) => api.post('/kafka/topic-metadata', data)
export const updateKafkaTopicMetadata = (id, data) => api.put(`/kafka/topic-metadata/${id}`, data)
export const deleteKafkaTopicMetadata = (id) => api.delete(`/kafka/topic-metadata/${id}`)
export const getKafkaGitOpsProfiles = (params) => api.get('/kafka/gitops-profiles', { params })
export const createKafkaGitOpsProfile = (data) => api.post('/kafka/gitops-profiles', data)
export const updateKafkaGitOpsProfile = (id, data) => api.put(`/kafka/gitops-profiles/${id}`, data)
export const deleteKafkaGitOpsProfile = (id) => api.delete(`/kafka/gitops-profiles/${id}`)
export const runKafkaGitOpsSync = (id) => api.post(`/kafka/gitops-profiles/${id}/sync`)
export const getKafkaGitOpsSyncs = (params) => api.get('/kafka/gitops-syncs', { params })
export const getKafkaCloudAdapters = (params) => api.get('/kafka/cloud-adapters', { params })
export const createKafkaCloudAdapter = (data) => api.post('/kafka/cloud-adapters', data)
export const updateKafkaCloudAdapter = (id, data) => api.put(`/kafka/cloud-adapters/${id}`, data)
export const deleteKafkaCloudAdapter = (id) => api.delete(`/kafka/cloud-adapters/${id}`)
export const getKafkaLineageRelations = (params) => api.get('/kafka/lineage', { params })
export const createKafkaLineageRelation = (data) => api.post('/kafka/lineage', data)
export const updateKafkaLineageRelation = (id, data) => api.put(`/kafka/lineage/${id}`, data)
export const deleteKafkaLineageRelation = (id) => api.delete(`/kafka/lineage/${id}`)
export const getKafkaLifecyclePolicies = (params) => api.get('/kafka/lifecycle-policies', { params })
export const getKafkaMeshGatewayConfigs = (params) => api.get('/kafka/mesh-gateway-configs', { params })
export const createKafkaMeshGatewayConfig = (data) => api.post('/kafka/mesh-gateway-configs', data)
export const updateKafkaMeshGatewayConfig = (id, data) => api.put(`/kafka/mesh-gateway-configs/${id}`, data)
export const deleteKafkaMeshGatewayConfig = (id) => api.delete(`/kafka/mesh-gateway-configs/${id}`)
export const getKafkaCostRecords = (params) => api.get('/kafka/cost-records', { params })
export const generateKafkaCostRecord = (data) => api.post('/kafka/cost-records/generate', data)
export const getKafkaSensitiveRules = (params) => api.get('/kafka/sensitive-rules', { params })
export const createKafkaSensitiveRule = (data) => api.post('/kafka/sensitive-rules', data)
export const updateKafkaSensitiveRule = (id, data) => api.put(`/kafka/sensitive-rules/${id}`, data)
export const deleteKafkaSensitiveRule = (id) => api.delete(`/kafka/sensitive-rules/${id}`)
export const runKafkaSensitiveScan = (data) => api.post('/kafka/sensitive-scan/run', data)
export const getKafkaSensitiveResults = (params) => api.get('/kafka/sensitive-results', { params })
export const getKafkaSchemaRegistries = (params) => api.get('/kafka/schema-registries', { params })
export const createKafkaSchemaRegistry = (data) => api.post('/kafka/schema-registries', data)
export const updateKafkaSchemaRegistry = (id, data) => api.put(`/kafka/schema-registries/${id}`, data)
export const deleteKafkaSchemaRegistry = (id) => api.delete(`/kafka/schema-registries/${id}`)
export const getKafkaSchemaSubjects = (params) => api.get('/kafka/schema-subjects', { params })
export const getKafkaSchemaVersions = (params) => api.get('/kafka/schema-versions', { params })
export const getKafkaSchemaDetail = (params) => api.get('/kafka/schema-detail', { params })
export const checkKafkaSchemaCompatibility = (data) => api.post('/kafka/schema-compatibility', data)
export const getKafkaACLs = (params) => api.get('/kafka/acls', { params })
export const createKafkaACL = (data) => api.post('/kafka/acls', data)
export const deleteKafkaACL = (data) => api.post('/kafka/acls/delete', data)
export const getKafkaScramUsers = (params) => api.get('/kafka/scram-users', { params })
export const upsertKafkaScramUser = (data) => api.post('/kafka/scram-users', data)
export const deleteKafkaScramUser = (data) => api.post('/kafka/scram-users/delete', data)
export const getKafkaPrometheusPanels = () => api.get('/kafka/prometheus/panels')
export const queryKafkaPrometheus = (params) => api.get('/kafka/prometheus/query', { params })
export const queryKafkaPrometheusRange = (params) => api.get('/kafka/prometheus/query-range', { params })
