#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"
CONFIG_DIR="$ROOT_DIR/backend/config"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
STATE_DIR="$ROOT_DIR/.deploy"

log() {
  printf '[deploy] %s\n' "$*"
}

warn() {
  printf '[deploy][warn] %s\n' "$*" >&2
}

die() {
  printf '[deploy][error] %s\n' "$*" >&2
  exit 1
}

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    docker-compose "$@"
  else
    die "未找到 docker compose 或 docker-compose"
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "缺少命令: $1"
}

ensure_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    die "已创建 .env，请先按需修改其中的密码和地址后再重新执行。"
  fi
}

load_env() {
  ensure_env_file
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

escape_yaml() {
  local value="${1:-}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

validate_env() {
  [[ -n "${MYSQL_ROOT_PASSWORD:-}" ]] || die ".env 中缺少 MYSQL_ROOT_PASSWORD"
  [[ -n "${REDIS_PASSWORD:-}" ]] || die ".env 中缺少 REDIS_PASSWORD"
  [[ -n "${JWT_SECRET:-}" ]] || die ".env 中缺少 JWT_SECRET"

  if [[ "${MYSQL_ROOT_PASSWORD}" == ChangeThisMysqlRootPassword ]]; then
    warn "MYSQL_ROOT_PASSWORD 仍是示例值，建议立即修改。"
  fi
  if [[ "${REDIS_PASSWORD}" == ChangeThisRedisPassword ]]; then
    warn "REDIS_PASSWORD 仍是示例值，建议立即修改。"
  fi
  if [[ "${JWT_SECRET}" == ChangeThisJwtSecretToALongRandomString ]]; then
    warn "JWT_SECRET 仍是示例值，建议立即修改。"
  fi
}

render_backend_config() {
  mkdir -p "$CONFIG_DIR"
  mkdir -p "$STATE_DIR"

  if [[ -f "$CONFIG_FILE" && ! -f "${CONFIG_FILE}.bak" ]]; then
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
  fi

  cat > "$CONFIG_FILE" <<EOF
# Generated by deploy.sh. Manual edits may be overwritten on the next deploy.
server:
  port: ":8081"
  log_level: "$(escape_yaml "${SERVER_LOG_LEVEL:-info}")"

database:
  type: "mysql"
  auto_migrate: true
  mysql:
    host: "mysql"
    port: 3306
    username: "root"
    password: "$(escape_yaml "${MYSQL_ROOT_PASSWORD}")"
    database: "$(escape_yaml "${MYSQL_DATABASE:-kafka_console}")"
    charset: "utf8mb4"
    parse_time: true
    max_open_conns: 10
    max_idle_conns: 5

logging:
  format: "json"
  time_format: "2006-01-02 15:04:05"
  report_caller: true

prometheus:
  base_url: "$(escape_yaml "${PROMETHEUS_BASE_URL:-}")"
  timeout: 10

swagger:
  enabled: ${SWAGGER_ENABLED:-false}
  host: "$(escape_yaml "${SWAGGER_HOST:-localhost:8081}")"
  base_path: "/"

health:
  enabled: true
  endpoint: "/health"
  interval: ${HEALTH_INTERVAL:-30}

redis:
  host: "redis"
  port: 6379
  username: ""
  password: "$(escape_yaml "${REDIS_PASSWORD}")"
  db: 0

jwt:
  secret: "$(escape_yaml "${JWT_SECRET}")"
  expire-time: 3600
  refresh-expire-time: 604800
  exclude-paths:
    - /api/v1/system/login
    - /swagger/*
    - /metrics
    - /health
EOF

  log "已生成后端配置: $CONFIG_FILE"
}

wait_for_mysql() {
  log "等待 MySQL 就绪..."
  local retries=60
  local i
  for ((i = 1; i <= retries; i++)); do
    if compose exec -T mysql sh -c 'mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent' >/dev/null 2>&1; then
      log "MySQL 已就绪"
      return 0
    fi
    sleep 2
  done
  die "MySQL 在预期时间内未就绪"
}

import_sql_file() {
  local sql_file="$1"
  [[ -f "$sql_file" ]] || die "SQL 文件不存在: $sql_file"
  log "导入 $(basename "$sql_file")"
  compose exec -T mysql sh -c 'MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mysql -uroot "$MYSQL_DATABASE"' < "$sql_file"
}

db_is_initialized() {
  local table_count
  table_count="$(
    compose exec -T mysql sh -c "MYSQL_PWD=\"\$MYSQL_ROOT_PASSWORD\" mysql -uroot -Nse \"SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${MYSQL_DATABASE:-kafka_console}' AND table_name IN ('sys_menu','kafka_clusters');\""
  )"
  [[ "$table_count" == "2" ]]
}

init_db_if_needed() {
  local init_db="${INIT_DB:-true}"
  local force_init="${FORCE_INIT_DB:-false}"

  if [[ "$init_db" != "true" ]]; then
    log "INIT_DB=false，跳过 SQL 初始化"
    return 0
  fi

  if [[ "$force_init" != "true" ]] && db_is_initialized; then
    log "检测到数据库已初始化，跳过 SQL 导入。如需强制重建，请设置 FORCE_INIT_DB=true。"
    return 0
  fi

  import_sql_file "$ROOT_DIR/backend/sql/kafka_console_init.sql"
  import_sql_file "$ROOT_DIR/backend/sql/kafka_module.sql"
  log "数据库初始化完成"
}

up() {
  render_backend_config
  mkdir -p "${MYSQL_DATA_DIR:-$ROOT_DIR/data/mysql}" "${REDIS_DATA_DIR:-$ROOT_DIR/data/redis}"
  compose up -d mysql redis
  wait_for_mysql
  init_db_if_needed
  compose up -d --build devops-backend-svc frontend
  compose ps
  log "部署完成"
  log "前端访问地址: http://<server-ip>:${FRONTEND_PORT:-80}"
  log "后端健康检查: http://<server-ip>:${BACKEND_PORT:-8081}/health"
}

down() {
  compose down
}

restart() {
  compose restart
}

logs() {
  if [[ $# -gt 0 ]]; then
    compose logs -f "$1"
  else
    compose logs -f
  fi
}

status() {
  compose ps
}

init_db_only() {
  render_backend_config
  compose up -d mysql redis
  wait_for_mysql
  local original_force_init="${FORCE_INIT_DB:-false}"
  FORCE_INIT_DB=true
  init_db_if_needed
  FORCE_INIT_DB="$original_force_init"
}

usage() {
  cat <<EOF
用法:
  ./deploy.sh up        启动并部署全部服务
  ./deploy.sh down      停止服务
  ./deploy.sh restart   重启服务
  ./deploy.sh logs      查看全部日志
  ./deploy.sh logs mysql
  ./deploy.sh status    查看容器状态
  ./deploy.sh init-db   强制重新导入初始化 SQL
EOF
}

main() {
  require_cmd docker
  docker info >/dev/null 2>&1 || die "Docker 服务不可用，请先启动 Docker"
  load_env
  validate_env

  local action="${1:-up}"
  case "$action" in
    up)
      up
      ;;
    down)
      down
      ;;
    restart)
      restart
      ;;
    logs)
      shift || true
      logs "$@"
      ;;
    status)
      status
      ;;
    init-db)
      init_db_only
      ;;
    *)
      usage
      die "不支持的动作: $action"
      ;;
  esac
}

main "$@"
