package kafka

import (
	kafkactrl "devops-console-backend/internal/controllers/kafka"

	"github.com/gin-gonic/gin"
)

func RegisterKafkaRouters(apiGroup *gin.RouterGroup) {
	controller := kafkactrl.NewController()
	kafkaGroup := apiGroup.Group("/kafka")
	{
		clusterGroup := kafkaGroup.Group("/clusters")
		{
			clusterGroup.GET("", controller.ListClusters)
			clusterGroup.GET("/options", controller.ListClusterOptions)
			clusterGroup.GET("/:id", controller.GetCluster)
			clusterGroup.POST("", controller.CreateCluster)
			clusterGroup.PUT("/:id", controller.UpdateCluster)
			clusterGroup.DELETE("/:id", controller.DeleteCluster)
			clusterGroup.POST("/:id/test", controller.TestClusterConnection)
		}
		kafkaGroup.GET("/dashboard", controller.GetDashboard)
		kafkaGroup.GET("/health", controller.GetHealthOverview)
		kafkaGroup.GET("/trends", controller.GetTrendSeries)
		kafkaGroup.POST("/topics", controller.CreateTopic)
		kafkaGroup.GET("/topics", controller.ListTopics)
		kafkaGroup.DELETE("/topics/:topic", controller.DeleteTopic)
		kafkaGroup.PUT("/topics/:topic/config", controller.UpdateTopicConfig)
		kafkaGroup.GET("/topics/:topic/partitions", controller.GetTopicPartitions)
		kafkaGroup.POST("/topics/:topic/partitions", controller.IncreaseTopicPartitions)
		kafkaGroup.GET("/brokers", controller.ListBrokers)
		kafkaGroup.GET("/consumer-groups", controller.ListConsumerGroups)
		kafkaGroup.GET("/consumer-groups/:groupId", controller.GetConsumerGroupDetail)
		kafkaGroup.POST("/consumer-groups/:groupId/reset-offset", controller.ResetConsumerGroupOffset)
		kafkaGroup.GET("/messages", controller.BrowseMessages)
		kafkaGroup.POST("/messages/produce", controller.ProduceMessage)
		kafkaGroup.GET("/audit-logs", controller.ListAuditLogs)
		kafkaGroup.GET("/alert-rules", controller.ListAlertRules)
		kafkaGroup.POST("/alert-rules", controller.CreateAlertRule)
		kafkaGroup.PUT("/alert-rules/:id", controller.UpdateAlertRule)
		kafkaGroup.DELETE("/alert-rules/:id", controller.DeleteAlertRule)
		kafkaGroup.POST("/alert-rules/evaluate", controller.EvaluateAlertRules)
		kafkaGroup.GET("/alert-silences", controller.ListAlertSilences)
		kafkaGroup.POST("/alert-silences", controller.CreateAlertSilence)
		kafkaGroup.PUT("/alert-silences/:id", controller.UpdateAlertSilence)
		kafkaGroup.DELETE("/alert-silences/:id", controller.DeleteAlertSilence)
		kafkaGroup.GET("/alert-events", controller.ListAlertEvents)
		kafkaGroup.PUT("/alert-events/:id/status", controller.UpdateAlertEventStatus)
		kafkaGroup.GET("/traces", controller.ListTraceLinks)
		kafkaGroup.POST("/traces", controller.CreateTraceLink)
		kafkaGroup.DELETE("/traces/:id", controller.DeleteTraceLink)
		kafkaGroup.GET("/scaling-recommendations", controller.GenerateScalingRecommendations)
		kafkaGroup.POST("/inspections/run", controller.RunInspection)
		kafkaGroup.GET("/inspections", controller.ListInspectionReports)
		kafkaGroup.GET("/inspections/:id", controller.GetInspectionReport)
		kafkaGroup.GET("/self-healing-policies", controller.ListSelfHealingPolicies)
		kafkaGroup.POST("/self-healing-policies", controller.CreateSelfHealingPolicy)
		kafkaGroup.PUT("/self-healing-policies/:id", controller.UpdateSelfHealingPolicy)
		kafkaGroup.DELETE("/self-healing-policies/:id", controller.DeleteSelfHealingPolicy)
		kafkaGroup.POST("/self-healing-policies/:id/execute", controller.ExecuteSelfHealingPolicy)
		kafkaGroup.GET("/self-healing-executions", controller.ListSelfHealingExecutions)
		kafkaGroup.GET("/tasks", controller.ListTasks)
		kafkaGroup.POST("/tasks", controller.CreateTask)
		kafkaGroup.PUT("/tasks/:id", controller.UpdateTask)
		kafkaGroup.DELETE("/tasks/:id", controller.DeleteTask)
		kafkaGroup.POST("/tasks/:id/run", controller.RunTask)
		kafkaGroup.GET("/task-runs", controller.ListTaskRuns)
		kafkaGroup.GET("/change-requests", controller.ListChangeRequests)
		kafkaGroup.POST("/change-requests", controller.CreateChangeRequest)
		kafkaGroup.PUT("/change-requests/:id/review", controller.ReviewChangeRequest)
		kafkaGroup.POST("/change-requests/:id/execute", controller.ExecuteChangeRequest)
		kafkaGroup.GET("/topic-metadata", controller.ListTopicMetadata)
		kafkaGroup.POST("/topic-metadata", controller.CreateTopicMetadata)
		kafkaGroup.PUT("/topic-metadata/:id", controller.UpdateTopicMetadata)
		kafkaGroup.DELETE("/topic-metadata/:id", controller.DeleteTopicMetadata)
		kafkaGroup.GET("/gitops-profiles", controller.ListGitOpsProfiles)
		kafkaGroup.POST("/gitops-profiles", controller.CreateGitOpsProfile)
		kafkaGroup.PUT("/gitops-profiles/:id", controller.UpdateGitOpsProfile)
		kafkaGroup.DELETE("/gitops-profiles/:id", controller.DeleteGitOpsProfile)
		kafkaGroup.POST("/gitops-profiles/:id/sync", controller.RunGitOpsSync)
		kafkaGroup.GET("/gitops-syncs", controller.ListGitOpsSyncs)
		kafkaGroup.GET("/cloud-adapters", controller.ListCloudAdapters)
		kafkaGroup.POST("/cloud-adapters", controller.CreateCloudAdapter)
		kafkaGroup.PUT("/cloud-adapters/:id", controller.UpdateCloudAdapter)
		kafkaGroup.DELETE("/cloud-adapters/:id", controller.DeleteCloudAdapter)
		kafkaGroup.GET("/lineage", controller.ListLineageRelations)
		kafkaGroup.POST("/lineage", controller.CreateLineageRelation)
		kafkaGroup.PUT("/lineage/:id", controller.UpdateLineageRelation)
		kafkaGroup.DELETE("/lineage/:id", controller.DeleteLineageRelation)
		kafkaGroup.GET("/lifecycle-policies", controller.GenerateLifecyclePolicies)
		kafkaGroup.GET("/mesh-gateway-configs", controller.ListMeshGatewayConfigs)
		kafkaGroup.POST("/mesh-gateway-configs", controller.CreateMeshGatewayConfig)
		kafkaGroup.PUT("/mesh-gateway-configs/:id", controller.UpdateMeshGatewayConfig)
		kafkaGroup.DELETE("/mesh-gateway-configs/:id", controller.DeleteMeshGatewayConfig)
		kafkaGroup.GET("/cost-records", controller.ListCostRecords)
		kafkaGroup.POST("/cost-records/generate", controller.GenerateCostRecord)
		kafkaGroup.GET("/sensitive-rules", controller.ListSensitiveRules)
		kafkaGroup.POST("/sensitive-rules", controller.CreateSensitiveRule)
		kafkaGroup.PUT("/sensitive-rules/:id", controller.UpdateSensitiveRule)
		kafkaGroup.DELETE("/sensitive-rules/:id", controller.DeleteSensitiveRule)
		kafkaGroup.POST("/sensitive-scan/run", controller.RunSensitiveScan)
		kafkaGroup.GET("/sensitive-results", controller.ListSensitiveResults)
		kafkaGroup.GET("/schema-registries", controller.ListSchemaRegistries)
		kafkaGroup.POST("/schema-registries", controller.CreateSchemaRegistry)
		kafkaGroup.PUT("/schema-registries/:id", controller.UpdateSchemaRegistry)
		kafkaGroup.DELETE("/schema-registries/:id", controller.DeleteSchemaRegistry)
		kafkaGroup.GET("/schema-subjects", controller.ListSchemaSubjects)
		kafkaGroup.GET("/schema-versions", controller.ListSchemaVersions)
		kafkaGroup.GET("/schema-detail", controller.GetSchemaDetail)
		kafkaGroup.POST("/schema-compatibility", controller.CheckSchemaCompatibility)
		kafkaGroup.POST("/discovery/scan", controller.ScanKafkaNetwork)
		kafkaGroup.POST("/discovery/import", controller.ImportDiscoveredKafka)
		kafkaGroup.GET("/acls", controller.ListACLs)
		kafkaGroup.POST("/acls", controller.CreateACL)
		kafkaGroup.POST("/acls/delete", controller.DeleteACL)
		kafkaGroup.GET("/scram-users", controller.ListScramUsers)
		kafkaGroup.POST("/scram-users", controller.UpsertScramUser)
		kafkaGroup.POST("/scram-users/delete", controller.DeleteScramUser)
		kafkaGroup.GET("/prometheus/panels", controller.GetPrometheusPanels)
		kafkaGroup.GET("/prometheus/query", controller.QueryPrometheus)
		kafkaGroup.GET("/prometheus/query-range", controller.QueryPrometheusRange)
	}
}
