FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/alpine:3.20.2

ENV TZ=Asia/Shanghai
WORKDIR /app

COPY devops ./

RUN addgroup -S app && adduser -S -G app app && chmod +x ./devops && chown app:app ./devops

EXPOSE 8081

USER app

CMD ["./devops"]
