apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-console.fullname" . }}-secret
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.secretEnv.MYSQL_HOST | quote }}
  MYSQL_PORT: {{ .Values.secretEnv.MYSQL_PORT | quote }}
  MYSQL_DATABASE: {{ .Values.secretEnv.MYSQL_DATABASE | quote }}
  MYSQL_USERNAME: {{ .Values.secretEnv.MYSQL_USERNAME | quote }}
  MYSQL_PASSWORD: {{ .Values.secretEnv.MYSQL_PASSWORD | quote }}
  REDIS_HOST: {{ .Values.secretEnv.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.secretEnv.REDIS_PORT | quote }}
  REDIS_PASSWORD: {{ .Values.secretEnv.REDIS_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
